name: npmjs
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 1 1 * *'
  workflow_dispatch:
jobs:
  read_npmjs:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Clone local repository locally
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: 17
    - name: Run everything in the same step
      run: |
        sudo apt update
        sudo apt install curl -y
        curl -s "https://get.sdkman.io" | bash
        source "/home/runner/.sdkman/bin/sdkman-init.sh"
        sdk help
        sdk install jbang
        mkdir target
        jbang scripts/ExtractPopularNpmjsArtifacts.java --output target/artifacts.json
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: reports_npmjs
        FOLDER: target
        TARGET_DIR: npmjs
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MESSAGE: Updated npmjs infos
        COMMIT-NAME: 🤖 GitHub Action
        COMMIT_EMAIL: get_npmjs_infos.yaml@github.actions