name: On GitHub release created

on:
  release:
    types:
      - created
  push:
    branches:
    - "bugs/27_cant_create_package"
  

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - id: release_number
        name: Get release version number to have it injected into maven
        uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          latest: true
      - name: Show next version number
        env:
          VERSION: "${{steps.release_number.outputs.tag_name}}"
        run:  echo "Next version will be $VERSION" 

#      - uses: actions/checkout@v4
#      - uses: actions/setup-java@v4
#        with:
#          distribution: adopt
#          java-version: 21
#          cache: 'maven'
#      - name: Publish package
#        run: "mvn --batch-mode deploy -Drelease={{steps.release_number.outputs.release}}"
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}