name: On GitHub release created

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - id: release_number
        name: Get release version number to have it injected into maven
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: Riduidel
          repo: aadarchi-technology-detector
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 21
          cache: 'maven'
      - name: Publish package
        run: "mvn --batch-mode deploy -Drelease={{steps.release_number.outputs.release}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}