name: On schedule execute code
on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

permissions:
  packages: read
# Allow only one concurrent run
concurrency:
  group: "camel-quarkus-run"
  cancel-in-progress: true

jobs:
  fetch_popular_libraries:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .dvcignore
            data.dvc
      - uses: iterative/setup-dvc@v1
      - name: Get latest version from repo
        id: version
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: Riduidel
          repo: aadarchi-technology-detector
      - run: echo "Using version $VERSION"
        env:
          VERSION: "${{steps.version.outputs.release}}"
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 21
          # We can't use cache for maven, since there will be no pom here
#          cache: maven
      # The mess with the settings is due to the fact that we push our artifacts to github packages, instead of maven central
      - name: Configure maven to use github packages
        uses: s4u/maven-settings-action@v3.0.0
        with:
          override: true
          githubServer: false
          servers: |
            [
              {
                "id": "github",
                "username": "${{ env.GITHUB_ACTOR }}",
                "password": "Bearer ${{ secrets.GITHUB_TOKEN }}",
                "configuration": {
                  "httpHeaders": {
                    "property": {
                      "name": "Authorization",
                      "value": "Bearer ${{ secrets.GITHUB_TOKEN }}"
                    }
                  }
                }
              }
            ]
          repositories: |
            [
              {
                "id":"central",
                "url":"https://repo1.maven.org/maven2"
              },
              {
                "id":"github",
                "name":"github",
                "url":"https://maven.pkg.github.com/Riduidel/aadarchi-technology-detector",
                "snapshots":{"enabled":true}
              }
            ]
      - name: Download artifact in current folder
        run: |
          mvn dependency:copy \
            -Dartifact=org.ndx.aadarchi.technology-detector:fetch-popular-artifacts:$VERSION:jar:runner \
            -DoutputDirectory=. \
            -DstripClassifier=true \
            -DstripVersion=true

        env:
          VERSION: "${{steps.version.outputs.release}}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run everything in the same step
        run: |
          java -Dtech-trends.github.token=${GITHUB_COM_TOKEN} -Dtech-trends.libraries.io.token=${LIBRARIES_IO_TOKEN} -jar fetch-popular-artifacts-$VERSION-runner.jar
        env:
          VERSION: "${{steps.version.outputs.release}}"
          GITHUB_COM_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          LIBRARIES_IO_TOKEN: ${{ secrets.LIBRARIES_IO_TOKEN }}
#      - name: Deploy
#        uses: s0/git-publish-subdir-action@develop
#        env:
#          REPO: self
#          BRANCH: reports_pypi
#          FOLDER: target
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          MESSAGE: Updated npmjs infospypi
#          COMMIT-NAME: 🤖 GitHub Action
#          COMMIT_EMAIL: get_pypi_infos.yaml@github.actions